sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t mike/docker-react -f Dockerfile.dev .
    
script: 
  - docker run -e CI=true mike/docker-react npm run test
